### ISSUE TITLE
Request for Install/Setup Guide

### ISSUE THREAD

**Issue by mahmoud-hamdan99** [khalifa005/e-proc#1]
Hi there!

I’ve been trying to get started with your project, but I’m having some difficulty understanding the installation and setup process. Would it be possible for you to provide a detailed guide on how to get the project up and running? A step-by-step installation and setup guide would be really helpful for new users.

Thanks in advance, and I appreciate the work you’ve put into this project!

**Comment by khalifa005** [comment]
If you're using a newer version of Angular and Node, you might encounter dependency issues. To resolve this, you can run:

npm install --legacy-peer-deps

Then, to serve your application with NX, use the following command:

npx nx serve host --devRemotes=service1


I also recommend starting fresh with a new NX Angular project using the latest versions. You can then migrate the required components and structure to the new project.

This approach ensures compatibility and makes it easier to maintain the project, especially as I’m currently recreating it to support the Knight Template. the upcoming Moon Knight Ultimate (Version 2) but still in progress and it wil be in a new project :
https://github.com/khalifa005/KnightArchitecture?tab=readme-ov-file#upcoming-in-version-2-ultimate-knight-hedge
